PlayCover/PlayTools

PlayTools/Controls/PlayAction.swift

This PR focuses on the following problems with the joystick control:
1. After using the joystick, when pressing option to call the cursor out, **a touch may be recognized** at the center of the joystick.
2. For Genshin, after using the joystick, after openning the in-game map using a mapped key (the M key normally) and pressing option to call the cursor out, the **map appears unable to be dragged**.
3. When pressing and releasing a joystick key very quickly (in less than 0.04s, according to the code), the pressed key is not released correctly, and **that key appears kept pressed**.
4. When the placement position of the joystick is not perfectly aligned with the in-game joystick, at the start of a joystick touch, the in-game joystick may shortly (for 0.04s, according to the code) **point …

Fix some joystick problems

---

PlayTools/Utils/Toast.swift

A toast is the message area that appears at the bottom of the window to show you a line of text when you do some action. For example, when you click cmd+k to open keymapping editor mode, a toast is displayed telling you "Click to start keymapping edit".
Based on the functionality of a toast, we think that a toast does not receive user interactions, but only shows messages. However, the play tool's toast does receive user interactions, making the elements behind it, including the game, unable to receive touch events.
For example, consider the game and keymapping shown in the image above. The toast area is on top of the mapped "RMB", "E", "Q" and "Z" keys. When the keymapping editor mode is closed, a toast saing "Keymapping saved" appears. Before that toast disappears (which takes 2.5 …

Fix: disable toast user interaction

---

PlayTools/PlayLoader.m
PlayTools/PlaySettings.swift

This Pull request aims to change the Ipad model identifier by reading pc.ipadModel key value on playcover.plist.

Adding Ipad model switcher

---

PlayTools/Controls/PlayInput.swift

Fixes https://github.com/PlayCover/PlayCover/issues/145
ESC key and function keys have long been used as mapped keys in official keymaps for games like Genshin, yet manually binding them is still impossible. The cause is simply a forbid list that explictly forbids binding of these keys. 
The reason why these keys are forbidden is unclear. That forbid list has not been altered since first commit from iVoider. Since people are already binding these keys by directly editing the keymapping file, this change should not introduce more problems.

Fix ESC and function keys mappings cannot be added

---

PlayTools/Controls/PlayAction.swift
PlayTools/Controls/PlayInput.swift
PlayTools/Keymap/EditorController.swift

This PR aims to solve the following problems:
1. When keymapping is enabled, cmd+Q does not work.
2. When switching keymapping editor mode, it often triggers multiple consecutive switchings.
By solving problem 1, this PR actually makes every command combination keys usable under keymapping mode, including cmd+Q, cmd+W and menu shortcuts.
The direct cause of the cmd+Q problem is the `fixBeepSound()` function inside playInput. 
As far as I can understand, the way playTools handle keyboard input is out of the typical event framework. In the typical framework, event handlers form a chain. If one handler does not handle an event, that event is passed to the next handler. If no handler claims to handle an event, the framework knows this and emits a "Beep" sound to indicate this key press is …

Fix editor mode switching and command Q

---

PlayTools/PlayCover.swift

Existing code uses `exit(0)` to terminate the app when its window is closed. This may miss some termination jobs that may be essential to some games. See the discussions [here.](https://stackoverflow.com/questions/25258424/difference-between-ways-to-quit-an-application-exit-nsapp-nsapplication-term)
The method proposed here is also used at `PlayUI.swift:25`. So it has a good chance to be OK.

gracefully terminate the game when close window

---

PlayTools/Controls/PTFakeTouch/PTFakeMetaTouch.h
PlayTools/Controls/PTFakeTouch/PTFakeMetaTouch.m
PlayTools/Controls/PTFakeTouch/addition/UIAccessibilityElement-KIFAdditions.m
PlayTools/Controls/PTFakeTouch/addition/UIApplication-KIFAdditions.m
PlayTools/Controls/PTFakeTouch/addition/UITouch-KIFAdditions.m
PlayTools/Controls/PTFakeTouch/addition/UIView-KIFAdditions.m
PlayTools/Controls/PlayAction.swift
PlayTools/Controls/PlayMice.swift
PlayTools/Controls/Toucher.swift

Depends on #18 
Attempts to fix https://github.com/PlayCover/PlayCover/issues/116
Tests show that doing too much work on the main thread makes the touch events lag and lose. As the code beyond `Toucher` is already simple enough, it is decided to optimize the underlying library.
PTFakeTouch is the underlying library that playtools use to send touch events. However, this library was initially only a proof of concept and not optimized. Specifically, for every touch event, it sends 100 touch points at once, while in practice usually only 2~4 points are pressed at the same time and needs to be sent at once. 
To make things worse, the `kif_setEventWithTouches()` function at `UIEvent+KifAdditions.m:55` , which is called by `eventWithTouches()` at `PTFakeMetaTouch.m:121`, would do lots of work on …

Optimize performance of PTFakeTouch

---

PlayTools/Controls/PlayAction.swift
PlayTools/Controls/PlayInput.swift
PlayTools/Controls/PlayMice.swift
PlayTools/Keymap/ControlModel.swift
PlayTools/Keymap/EditorController.swift

Some mobile games require the operation that the player press on some button and drag it to somewhere else, then release it to complete some action. In fact Genshin has this operation too. We just happen to work around this by a button press and a separate camera control. But this is not a natural human operation and may not work in other games.
The following video demonstrates how a draggable button can be used in a MOBA game. (it's the exact video I sent in the Discord server)
https://cdn.discordapp.com/attachments/996713647827066981/1013902534584320000/draggableButton.mp4
1. Create a mouse drag area
2. While focused on the mouse drag area, press any key on the keyboard
1. Press and hold the mapped key for the draggable button
2. Move mouse to move it's touch point
3. Release mapped key …

Feat: button-controlled mouse drag action

---

PlayTools/Controls/MenuController.swift
PlayTools/Controls/Toucher.swift
PlayTools/Keymap/DragElementsView.swift
PlayTools/Keymap/EditorController.swift
PlayTools/PlayScreen.swift
PlayTools/Utils/Toast.swift

Should fix https://github.com/PlayCover/PlayCover/issues/64
In some games, when opening the keymapping editor, the editor does not show, nor does the toast. But the switching does succeed, since cursor is hidden when editor is closed. The reason may be that the game is displaying it's content in a different UIWindow from where the editor and toast shows. 
Before this PR, code assumes there is only one UIWindow, and takes the first UIWindow object from the UIWindow array of this application as the only UIWindow. 
In this PR, the editor UI is moved to a new UIWindow. When editor is shown, this UIWindow is made visible. Otherwise, this UIWindow is made hidden. Although UIWindow can directly have subviews, doing so without a UIViewController prevents the UIWindow from setting it's orientation …

Fix: editor UI not shown in some games

---

PlayTools/Controls/ControlMode.swift
PlayTools/Controls/PlayAction.swift
PlayTools/Controls/PlayInput.swift
PlayTools/Controls/PlayMice.swift
PlayTools/PlaySettings.swift

Btw I have question.
Q: Does adaptive resolution should work only with games? If not we should make resolution's default value 0 for non-game app.
ps. I think mouse mapping and sensitivity settings in PlayCover's AppSettingView should disabled when key mapping is unchecked because mouse mapping is working only when key mapping is enabled.

fix: Add missing setting data to fix wrong behavior

---

PlayTools/Controls/PlayAction.swift
PlayTools/Controls/PlayMice.swift

Currently keymapping only supports mapping one key to at most one button. If multiple buttons have the same mapped key, only one of them works. 
In this PR, multiple buttons mapped to the same key can work at the same time. This is done by chaining event handlers for keyboard keys, and a stored action list for every mouse button.

Support mapping one key to multiple buttons

---

PlayTools/Controls/PTFakeTouch/PTFakeMetaTouch.h
PlayTools/Controls/PTFakeTouch/PTFakeMetaTouch.m
PlayTools/Controls/PTFakeTouch/addition/UITouch-KIFAdditions.h
PlayTools/Controls/PTFakeTouch/addition/UITouch-KIFAdditions.m
PlayTools/Controls/PlayMice.swift
PlayTools/Controls/Toucher.swift

Must have fixed https://github.com/PlayCover/PlayCover/issues/116
With this PR, it <del>makes renderring stuck too</del> does not stuck on fake touch as long as the frame rate does not drop dramatically. The code run on the main thread is executed via runloop's source0, which is the same as native event handling. And it is completely concurrent with fake touch thread. 
The source order is set as -1, which is the same as that of the native event handler. In theory, this should not be slower than if you really touch the screen with your finger. If it ever stutters, it should also stutter if you drag the screen by curcor.
I tested it by poping a toast for every mouse move event, which could end up with a hundred toasts on screen at the same time, which makes Genshin really stuck. Even in …

Dramatically improve fake touch efficiency

---

PlayTools/Controls/PlayMice.swift
PlayTools/PlayScreen.swift

Fixes https://github.com/PlayCover/PlayCover/issues/278
Playtools' way of faking touches handles multi-touch states in its own code. As a result, mouse input when mouse mapping is off, which does not go through fake touch, has no multi-touch ability with faked touches. 
This fix is done by identifying mouse click and move events in event handlers, stopping the events from propagating to UIApplication, instead making fake touch handles them. In this way fake touch has multi-touch info of mouse input, thus supporting multi-touch with mouse input.
There is some math in converting NSWindow coordinates to UIWindow coordinates. But it would be straight forward if you look at the code.
I was thinking about doing so by sending hardware touch events instead of directly handle UIEvent object, but …

Fix: multi-touch with mouse when mouse mapping is off

---

PlayTools/Controls/PlayMice.swift

FIxes https://github.com/PlayCover/PlayCover/issues/379 and https://github.com/PlayCover/PlayCover/issues/388
https://github.com/PlayCover/PlayTools/pull/10 fixed aiming and https://github.com/PlayCover/PlayTools/pull/34 changed logic of lifting off. Camera control code got too complicated after those two PRs. This PR cleans up the logic and changes some control parameters (i.e. when should camera touch point lift off) to fix the mentioned issues.
Direct cause of the issue is that the "slowness threshold" set too high. Some fast moves are recognised as slow moves. But instead of simply lowering the threshold, I also want to simplify the code, so that it's easier for others to understand.
Basically, camera control touch point must lift off at appropriate time, to prevent issues like in …

Improve camera control

---

PlayTools/Controls/PTFakeTouch/NSObject+Swizzle.m

Now the check for _UIMenuBuilder won't happen every single time an object is initialized.  Not only was this terrible for performance, the original hook is most likely the cause of some odd bugs.  For example, the hook may return an initialized object when it should return NULL and thus altering control flow in unpredictable ways.  Personal observation: I had two virtual synthesizers that would crash at random times before this fix. 
This change also fixes the endless `[MenuBuilder] Duplicates existing --` warnings when attached to a debugger.

Fix menubuilder swizzle

---

PlayTools/Controls/PTFakeTouch/NSObject+Swizzle.m

This PR changes the behaviour of the _UIMenuBuilder swizzle in order to address bugs both caused and fixed in https://github.com/PlayCover/PlayTools/commit/e3e422b1df55dc1e91cdd6ca1ba500fe31a7e6fb and https://github.com/PlayCover/PlayTools/pull/57 .
Among other things, #57 fixed a regression in game performance and a regression in the game Sonic the Hedgehog (see https://github.com/PlayCover/PlayCover/issues/578 for more information) caused both in https://github.com/PlayCover/PlayTools/commit/e3e422b1df55dc1e91cdd6ca1ba500fe31a7e6fb, and in turn caused a regression in which certain games wouldn't start PlayTools correctly. Such are the likes of Crossy Road, Dadish and Dadish 3.

Change behaviour of the _UIMenuBuilder swizzle

---

PlayTools/Controls/PTFakeTouch/NSObject+Swizzle.m
PlayTools/PlayCover.swift

The problem with seems to have been a combination of the delay in `initMenu` and/or apps having their own `NSObject` categories.
Fixes:
- Remove delay in `initMenu`
- Apply method swizzling from a class that will not have categories or subclasses (mildly "enforced" with a "hidden" attribute)

Fix PlayTools not loading for some apps in #57

---

PlayTools/Controls/PTFakeTouch/PTFakeMetaTouch.m
PlayTools/Controls/PlayAction.swift
PlayTools/Controls/PlayInput.swift
PlayTools/Controls/PlayMice.swift
PlayTools/Controls/Toucher.swift
PlayTools/PlayScreen.swift

When keymaps are loaded from the file, we assign an ID to each entry, which are later used as the touch point ID for that touch action. This method assumes that every touch action uses only one touch point, or at least unnecessarily exposes implementation details of how many touch points an action uses to a higher abstraction layer.
After this PR, when an action starts a touch point, it gets the touch point ID from the toucher. In the `Action` layer, we no longer need to assign a touch point ID in advance, but only need a variable (or multiple variables if it uses multiple touch points) to store the returned touch point ID. The refactor also makes it possible to store infinitely many entries in a keymap (previously has a upper limit of 100).
This refactor makes it easier to add new type …

Toucher Refactor: decouple touch point ID from touch action ID

---

AKPlugin.swift
PlayTools/Controls/PlayAction.swift
PlayTools/Controls/PlayInput.swift
PlayTools/Controls/PlayMice.swift
PlayTools/Controls/Toucher.swift
PlayTools/Keymap/EditorController.swift
PlayTools/PlayScreen.swift
Plugin.swift

Depends on #69 
This PR enhances camera control, so that mouse scroll wheel can be used to scale camera in and out.
Additionally, when cursor is shown, scroll wheel is mapped to drag the screen, so that scroll wheel can be used to scroll menus.

Zoom camera in and out with scroll wheel

---

PlayTools/PlayLoader.m

While this is normally harmless, some apps (such as Amazon Kindle) do... strange things with their Keychain objects
This is tolerable for Keychain itself, but ABSOLUTELY NOT for ObjC and attempting to dereference them will lead to a crash because NSString can't format them

fix: Prevent ObjC object dereferencing if debugging is not enabled

---

PlayTools/Controls/ControlMode.swift
PlayTools/Controls/PlayInput.swift
PlayTools/Keymap/EditorController.swift
PlayTools/Utils/Toast.swift

Partly implemented #74 
https://user-images.githubusercontent.com/16048758/217622367-ceaf7b43-d8ca-4e8f-a301-14e626b81980.mov
5 seconds after launch, if keymapping is not enabled, a message would appear prompting the user to enable keymapping. In this case, when the user enables keymapping, the previous message disappears and a message would appear prompting the user to disable keymapping. In this case, when the user disables keymapping, the message would disappear. Both messages show at most once during each launch.
Keymapping editor open and close messages are also migrated to the new UI. The open message would stay there until the user closes the editor. The close message would stay for 3 seconds.

Add new toast UI and operation hint message

---

PlayTools/Controls/PTFakeTouch/PTFakeMetaTouch.m
PlayTools/Controls/PlayAction.swift
PlayTools/Controls/PlayInput.swift
PlayTools/Controls/PlayMice.swift
PlayTools/Keymap/ControlModel.swift
PlayTools/Keymap/KeyCodeNames.swift
PlayTools/Keymap/Keymapping.swift

In the existing code, in the initialization of `action`s, event handlers are setup, so that this `action` can be executed whenever corresponding hardware input happens. While in `PlayInput` there are also event handler setups that serve purposes like keymap editor, it appears that there are multiple places setting up event handlers for the same input device.
This PR aims to construct a unified action registration mechanism, in which `action`s does not setup event handlers directly, but rather register their handlers to the _hardware abstraction layer_ (aka. `PlayInput` and `PlayMice`). The latter is responsible for dispatching hardware events to appropriate receivers.
This would make the code structure clearer and make it easier to add new features, like complete controller support.

Refactor input handlers

---

PlayTools/PlaySettings.swift

Fixed: 
- M2 iPad Pro
- iPhone 13 Pro Max
- iPhone 14 Pro Max
These had incorrect OEM IDs, the "A" numbers are in fact family numbers, not the proper internal board/hardware/OEM ID used to target software. For more info see this article on [Apple Device Identifiers](https://reincubate.com/support/deviceidentifier/apple-identifiers/#understanding-codes)
I used multiple sources to verify the accuracy of the IDs
M2 iPad Pro: [GeekBench](https://browser.geekbench.com/v5/cpu/20450186), [PhoneDB](https://phonedb.net/index.php?m=device&id=20871&c=apple_ipad_pro_12.9-inch_2022_6th_gen_a2436_wifi_2tb__apple_ipad_14,5), [iPhone Wiki](https://www.theiphonewiki.com/wiki/IPad_Pro_(12.9-inch)_(6th_generation))
13 Pro Max: [GeekBench](https://browser.geekbench.com/v5/cpu/10677798), …

Fix wrong OEM IDs 

---

PlayTools/Controls/PlayInput.swift
PlayTools/Utils/Toast.swift

Stored in `UserDefaults` a low precision timestamp indicating roughly when did the user last disabled keymapping in playtools. The hint would display when the user uses an APP for the first two times, or when the stored timestamp is more than 14 days to now.
The hint now has a timeout of 10 seconds.
I choose to display it twice for the first uses in case people missed it or forgot it.

Hint does not show every launch

---

PlayTools/Keymap/DragElementsView.swift

Lots of people get confued between "rounded square mouse" and "circle mouse". Most of them actually needs "circle mouse", which is used to control camera. "rounded square mouse" is used to control movement. 
To avoid confusion to new comers, I removed the option to add a "rounded square mouse" in keymapping editor's circle menu.
For people who do need this, you can set a mouse controlled joystick by clicking any mouse button except left mouse button (i.e. right mouse button or middle mouse button) while focused on a WASD joystick. 
It would be better if we have text to describe what can be done to add a new mapping and to an existing mapping. I have researched a little and find it impossible under the current editor architecture. Either a refactor to the current editor or a complete new …

Hide the option to add a mouse controlled joystick in circle menu

---

PlayTools/Controls/PTFakeTouch/NSObject+Swizzle.m

This patch fixes an issue where some video streaming apps may run for roughly half a second then quit unexpectedly

fix: void out unavailable VSS calls

---

PlayTools/PlaySettings.swift

Reverts PlayCover/PlayTools#81, this was pointing out to the wrong branch

Revert "Fix wrong OEM IDs "

---

PlayTools/Keymap/DragElementsView.swift

Accidentally cherry-picked in 6111a5db8e2efee63b3be4d9c76fc4c688f1e46a.

Fix showHint undefined in Toast

---

PlayTools/PlayLoader.m

There is a (small) chance that some apps may actually read `hw.model`, which may cause our buffer to not be long enough when calling the real `sysctl`

fix: small fix on buffer allocation

---

PlayTools/Controls/PlayAction.swift

In the WASD mapping, if you press W and S at the same time, the game character will move towards the later pressed direction. 
If you release a key, the expected behaviour is to move towards the other direction. However, current implementation is:
> For example, if I hold down W, I'll go up. And if at the same time I press S, I'll go down, but once I let go of S, I don't walk up anymore even though I'm still holding W.
This PR is to fix this issue.

Fix joystick opposite direction cancel each other

---

PlayTools/Controls/ControlMode.swift
PlayTools/Controls/PlayInput.swift
PlayTools/Controls/PlayMice.swift
PlayTools/Keymap/EditorController.swift
PlayTools/Utils/Toast.swift

Fix issues that if any mapped key is held while entering typing mode, the touch point would not release even if the key is released.
In the original design, only keyboard mapping is disabled when typing. 
This PR would also disable mouse and controller mapping, so that it could conveniently release all touch points.
Steps to reproduce the issue in Genshin:
1. Hold any key mapped but not on UI elements, say F
2. Click an input box to enter typing mode
3. Release F
4. Press Enter or Esc to exit typing mode
5. Hide cursor and move mouse. Now the expected behaviour is that camera moves, but the actual behaviour is that camera zooms.
Besides, this PR renames corresponding notification names from `KeymappingEnable/Disable` to `CursorHide/Show` to match the actual behaviour.

Fully disables input mapping when typing

---

AKPlugin.swift

Fixes the issue that draggable button could unexpectedly associate mouse and cursor when cursor is hidden.
Steps to reproduce:
1. Bind some key to draggable button, say E
2. Hide cursor
3. Press E and release it
4. Move mouse
5. Unhide cursor. The expected behavior is that the cursor appears at center. The actual behavior is that the cursor could appear somewhere else.

Fix draggable button associate mouse cursor

---

PlayTools/Controls/ControlMode.swift
PlayTools/Controls/PlayInput.swift
PlayTools/Controls/Toucher.swift
PlayTools/PlaySettings.swift
PlayTools/Utils/Toast.swift

Add an option to disable the newly introduced automatic keymapping toggle.
The issue being that some games don't correctly emit keyboard event and can cause weird behaviours when relied on

fix: auto keyboard toggle

---

PlayTools/Controls/PTFakeTouch/NSObject+Swizzle.m

In Sonoma14.1 betas, FBSSceneSettings seems to have ```- (CGRect) frame```, FBSSceneSettingsCore does.
It can be swizzled by using ```exchangeMethod```. 
These code needs to be edited for Sonoma under 14.1betas.

Patch for Sonoma14.1 betas

---

PlayTools/Controls/Backend/Action/PlayAction.swift
PlayTools/Controls/Frontend/ControlMode.swift
PlayTools/Controls/Frontend/ModeAutomaton.swift

Fixes:
- Allowing keymap editor when keymaps are disabled (which fixes bug where user can't exit hidden cursor after closing editor)
- Buttons still being pressed after releasing cursor or opening keymap editor (such as pressing "w" for forward and then releasing cursor which causes the button to still be pressed). The actions should only be invalidated if smart keymap is disabled.
- Swipe action crashing after invalidation, but not deinitialized (caused by the fix above). After cancelling a timer, it cannot be resumed, so that is moved to the `deinit` function.

Fix minor keymap bugs

---

PlayTools/MysticRunes/PlayShadow.m

Temporarily gate this behind an envvar so it can't be enable from UI
Reportedly this is breaking Japan BA. I'll implement one with fishhook later

fix: temporarily disable extra jb bypass for release

---

PlayTools/Controls/MenuController.swift

The key mapping "rotate display" command disabled in the some games/apps. This patch executes the rotate command on `UIApplication` and find all the connected `UIWindow`. Then trigger the old `rotateView` method on root view controller.
Before:
After:

Fix "rotate display" menu action for some apps disabled issue

---

PlayTools/Controls/Frontend/ControlMode.swift
PlayTools/Controls/Frontend/ModeAutomaton.swift

Fixes bug where smart keymapping makes it so that the user is unable to type in textfields (such as game chat) with smart keymapping enabled. Also fixes an issue where elements on screen are unable to be clicked. Fixes https://github.com/PlayCover/PlayCover/issues/1086.

Fix smart keymapping disallowing textfield typing

---

PlayTools/PlayCover.swift

Fixes PlayCover/PlayCover/issues/689 and PlayCover/PlayCover/issues/1165
This issue occasionally occurs to Genshin Impact, but always happens for most other games. For example Ni No Kuni and ToF, which have 100% probability of encountering this. With this PR, neither of them crash or freeze anymore.
The root cause of this issue lies in the fact that the app is being forcefully terminated without completing its termination procedures. These procedures may involve ending metal commands and synchronizing data to disk, among other things. In the worst-case scenario, if these termination tasks are not completed successfully, it can result in data corruption and lead to the game crashing upon subsequent launches.
This PR follows the termination procedures …

Fix app crash or freeze on quit

---

PlayTools/MysticRunes/PlayedApple.swift

(This is my guess) Maybe Apple has made the keychain dictionary immutable, so this would blow up
Should fix https://github.com/PlayCover/PlayCover/issues/1240

fix: rref dictionary crash (da heck apple)

---

PlayTools/MysticRunes/PlayedApple.swift

https://github.com/PlayCover/PlayCover/issues/1359
First, there is a need for a response from SecItemDelete with `errSecItemNotFound` in some iOS framework, as it works well on iOS. 
Second, the linked iOS app had a memory issue with ARC and `SecCreateKeyWithData`, I think it is weird that it require Unmanaged.passRetained but it crashed every time with unknownObjectReleasing every time end of SecItem methods in the app, and SecItem-methods do not have responsibility for releasing the referenced object `*result`. [https://developer.apple.com/documentation/security/1401659-secitemadd]

Fix some SecItem methods hook in PlayChain.

---

PlayTools/Controls/Frontend/EventAdapter/Mouse/Instances/TouchscreenMouseEventAdapter.swift

When smart keymap is enabled and cursor is shown and you operate this thing:
It fails.
It seems draggable button was simply not processed in `ARBITRARY_CLICK` mode, which corresponds to `TouchscreenMouseEventAdapter.swift`
Must have been a mistake during last refactor.

Fix draggable button unusable when cursor is shown

---

PlayTools/Controls/Backend/Action/PlayAction.swift
PlayTools/Controls/Frontend/ControlMode.swift

Fixes some Wuthering Waves pointer issue
Previously, playcover would deliver a touch event to the game whenever a mouse event arrives. However, some mouses have poll rate over 1000 which is far beyond the designed processing ability of a touchscreen game.
In this PR, a swipe action's polling rate is limited to no more than 125, so as to fix some issues caused by high polling rate.
This might also fix PlayCover/PlayCover/issues/1483, in such a case: that the touching system is overwhelmed by too many move events, and the system decides to randomly drop some events, and eventually drops a touch_end event. If people are reporting it only on mouse but not touchpad, that could be this case.  
Personally I'm playing with a touchpad and everything works perfectly. I don't have a working mouse so …

Limit max polling rate

---

PlayTools/Controls/ActionDispatcher.swift
PlayTools/Controls/Backend/Action/PlayAction.swift
PlayTools/Controls/Frontend/ControlMode.swift
PlayTools/Controls/PTFakeTouch/PTFakeMetaTouch.m

Fixes PlayCover/PlayCover/issues/1483 and PlayCover/PlayCover/issues/767 and PlayCover/PlayCover/issues/1492
I think I finally found the real cause (many thanks to testing help of discord user @Tyler): The data race in `PTFakeMetaTouch`
Basically a `reusageMask` is used to record allocation of `UITouch` objects to touch points. The fake touch process has two procedures, `sendEventCallback` runs in main thread, and `touchcam` runs in `touchqueue` which is a separate thread. For `reusageMask`, there is a `&=` operation in `touchqueue` and a `|=` operation in main thread. 
Theoretically, there should be some protection method on this cross-thread data manipulation, but for some reason there are not. How could this cause the random zoom-in zoom-out issue?
So the `&=` operation in `touchcam` …

Fix random zoom in zoom out

---

PlayTools/Controls/Backend/Action/PlayAction.swift

After the keymap loads, if the first fake mouse event is a key release event (instead of a key pressed event), the game would crash.
Open any game. Switch to another window. Press left mouse button and while holding it, switch to the game window with cmd+tab. Release left mouse button inside game window, the game will crash.
To trigger the issue, mouse can't have any clicks in the game window before that release action. Or you can open keymap editor then close it, that would re-load the keymap and "clear" previous clicks.
The mouse position is obtained in mouse pressed event and mouse moved event. And the position variable was force unwrapped. So if a released event comes before any pressed event or moved event (actually no moved event would reach there if there were no pressed event, as …

Fix fake mouse occasionally crash

---

PlayTools/Controls/Backend/Action/PlayAction.swift

Fixes PlayCover/PlayCover/issues/1022
Two touch points starting from the center of camera action plus/minus 100 in y axis and not changing the x axis, moving towards each other with velocity exponentially decrease and apart from each other exponentially increase.
Two touch points starting from upper/lower 1/4 equally divider point of the screen, with x axis in the center and y axis having equal distance to up/bottom edge and center. The moving speed is as the scroll wheel's is, but touches would lift off when they're to touch each other or to touch edge.
Actually #144 already limited touch points inside window, so that the exact glitch of PlayCover/PlayCover/issues/1022 no longer happens. But that also breaks how original scroll wheel zooming function works and makes it randomly move …

Fix scroll wheel zoom glitch

---

AKPlugin.swift
PlayTools/Controls/Frontend/ControlMode.swift
PlayTools/Controls/Frontend/EventAdapter/Keyboard/Instances/EditorKeyboardEventAdapter.swift
PlayTools/Controls/Frontend/EventAdapter/Keyboard/Instances/TouchscreenKeyboardEventAdapter.swift
PlayTools/Controls/Frontend/EventAdapter/Keyboard/Instances/TransparentKeyboardEventAdapter.swift
PlayTools/Controls/Frontend/EventAdapter/Keyboard/KeyboardEventAdapter.swift
Plugin.swift

Implements #124 
Managed to implement this without breaking keymap format compatibility, by prepending a `⌃` symbol before the key name to mark it a modifier combination.
As Control key is now used as a modifier key, it can't be mapped separately any more. But existing keymaps with Control key mapped can still use it.
Can only map `Button` type actions, this excludes `DraggableButton` and `Joystick`. It's because these two mainly rely on key code (instead of key name) to distinguish different keys. It's further because of the underlying keymap format, in which there are not enough fields for key name for these types.

Support mapping Control key modifier combination

---

PlayTools/Controls/PlayInput.swift
PlayTools/PlayTools.h

Fixes Playcover/Playcover/issues/1550
The issue is basically the same as #83. Testing and analysis shows that some games rely on GameController APIs (which in turn relies on main dispatch queue) to process controller input. But main dispatch queue may not be served in time for some reason.
`CFRunLoop` of the main thread typically drains the main dispatch queue. It eventually calls `_dispatch_main_queue_callback_4CF()` to do its work. In PlayTools, by calling this function every frame, the input can be processed timely. This is done via the `CADisplayLink`, which is a timer that gets called every frame, originally designed for handling UI drawing routines.
With this fix, I have played ZZZ with an XBox controller on my M1 pro Macbook, with ProMotion on, low power mode on, keymapping on, …

Fix controller input lag or unresponsive in some games

---

PlayTools.xcodeproj/project.pbxproj
PlayTools/Controls/PTFakeTouch/NSObject+Swizzle.m
PlayTools/Utils/BatteryLevel.h
PlayTools/Utils/BatteryLevel.m

Some games use the device battery level and can cause some games to not work/show incorrect value. This commit fix it passing a 100% battery 
https://github.com/PlayCover/PlayCover/issues/1522

Fix BatteryLevel not available

---

AKPlugin.swift
PlayTools/Controls/MenuController.swift
Plugin.swift

Add support to hide pointer even if you r using a controller with cmd+.
Asked here https://github.com/PlayCover/PlayCover/issues/1599

Added option to hide mouse pointer

---

PlayTools/PlayLoader.m

The file name ue4commandline.txt has been changed to uecommandline.txt in UE5.
Some applications mistakenly use both Library\Users and Documents\Users paths multiple times within a single path, more often than I expected.
To address this, I ensure that PlayTools retrieves the string from the last needle of the incorrect path.
Issue: https://github.com/PlayCover/PlayCover/issues/1755

Update for UnrealEngine's wrong file path

---

PlayTools/Controls/PTFakeTouch/NSObject+Swizzle.m
PlayTools/PlayLoader.m
PlayTools/Utils/PlayInfo.swift

Recently some Unreal Engine games started using the [Extended Virtual Addressing](https://developer.apple.com/documentation/bundleresources/entitlements/com.apple.developer.kernel.extended-virtual-addressing) feature. When this feature is enabled, Unreal Engine attempts to extract the Entitlement from the executable and checks whether it contains `com.apple.developer.kernel.extended-virtual-addressing`.
However, due to an issue in Unreal Engine’s code, it read **8 extra bytes**. These extra bytes cause a string decoding failure when the system language is set to Chinese, ultimately leading to a crash.
[FApplePlatformMemory.cpp](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Runtime/Core/Private/Apple/ApplePlatformMemory.cpp#L874)
This function calls …

Fix a crash in Unreal Engine games when system language is Chinese

---

PlayTools/Controls/MenuController.swift

Use the new `UIMainMenuSystem` to configure the system menu to display the `Keymapping` menu.
Note:
The `UIMainMenuSystem` needs the macOS 26 Beta SDK. The fix is a temp patch and should not used for release. 
Please make a beta branch for the PR's target until OS Tahoe released.

Fix menu not display on macOS 26 issue

---

PlayTools/Controls/ActionDispatcher.swift
PlayTools/Controls/MenuController.swift
PlayTools/Editor/Controllers/EditorController.swift
PlayTools/Keymap/Keymapping.swift

Requires https://github.com/PlayCover/PlayCover/pulls/1567.

feat!: Multi-keymap

---

PlayTools/Controls/PTFakeTouch/NSObject+Swizzle.m
PlayTools/PlaySettings.swift

It was confirmed that some games suffer from excessive CPU usage.
This is caused by `CMMotionManager` setting the default update interval to 0, which results in extremely frequent updates.
You can verify the update frequency using the following code:
``` objective-c
// NSObject+Swizzle.mm
@implementation NSObject (Swizzle)
- (void)hook_UINSVirtualMotionDevice_scanAccelerometer {
NSLog(@"[PlayTools] hook_UINSVirtualMotionDevice_scanAccelerometer");
[self hook_UINSVirtualMotionDevice_scanAccelerometer];
}
@end
@implementation PTSwizzleLoader
+ (void)load {
[objc_getClass("UINSVirtualMotionDevice") swizzleInstanceMethod:NSSelectorFromString(@"_scanAccelerometer") withMethod:@selector(hook_UINSVirtualMotionDevice_scanAccelerometer)];
}
@end
```
<br/>
As shown below, the actual update interval …

Fix excessive CPU usage caused by motion sensor updates

---

PlayTools/Controls/PTFakeTouch/NSObject+Swizzle.m
PlayTools/Controls/PlayInput.swift
PlayTools/PlaySettings.swift

Many Unreal Engine games receive both touch and mouse inputs simultaneously, but they do not handle the mouse inputs properly, which leads to click issues.
To resolve these conflicts, we need to disable the app’s built-in mouse support.
<br/>
**Related Issues:**
1. https://github.com/PlayCover/PlayCover/issues/1587
All the games mentioned in this issue are made with Unreal Engine.
2. https://github.com/PlayCover/PlayCover/issues/1755
> The "Accept" user agreement button and "Login" button can only be triggered by a Trackpad tap but not a mouse click (not a MagicMouse).
<br/>
**Additional Note:**
`swizzleClassMethod:withMethod` is copied from `PlayShadow.m`.

Fix mouse click conflicts by disabling built-in mouse support
