PlayCover/PlayTools

PlayTools/PlayScreen.swift, PlayTools/PlaySettings.swift
In order to make this feature work you'll need to enable adaptive display
=> feat: ✨ Enabling windowed fullscreen mode

PlayTools/PlayCover.swift
This will make app quit when window is closed.
So pressing red close button on top or `Cmd + W` will quit the app.
=> feat: Quit app when close button on the top pressed

PlayTools/PlayCover.swift
https://github.com/PlayCover/PlayTools/pull/9#issuecomment-1210316583
=> fix: Fix app quitting when exiting full screen

PlayTools/Controls/PlayMice.swift
When aiming with a bow, the player fine-tunes the camera orientation to align with a distant object. 
With the current code, fine-tuning camera orientation is very difficult. The code lifts off the camera-draging touch point once it does not receive mouse move event in a frame. This causes that touch point repeatedly pressing down and lifting off during the aiming process. How does this make aiming hard?
The reason is a camera-drag-startup zone of games like Genshin. When a touch point moves on the screen, the game does not count it as a drag until it moves for sufficient distance. Which means, the first several move events of the touch point does not move the camera. 
Therefore, to make aiming easier, that touch point should try its best not to lift off during aiming. But why should we …
=> fix aiming problem

PlayTools/Controls/PTFakeTouch/PTFakeMetaTouch.h, PlayTools/Controls/PTFakeTouch/PTFakeMetaTouch.m, PlayTools/Controls/PTFakeTouch/addition/UIAccessibilityElement-KIFAdditions.m, PlayTools/Controls/PTFakeTouch/addition/UIApplication-KIFAdditions.m, PlayTools/Controls/PTFakeTouch/addition/UITouch-KIFAdditions.m, PlayTools/Controls/PTFakeTouch/addition/UIView-KIFAdditions.m, PlayTools/Controls/Toucher.swift
Also translates interface description of PTFakeTouch
=> Fix depracation warnings

PlayTools.xcodeproj/project.pbxproj, PlayTools/Controls/PlayAction.swift, PlayTools/Controls/PlayInput.swift, PlayTools/Controls/PlayMice.swift, PlayTools/Keymap/ControlModel.swift, PlayTools/Keymap/EditorController.swift, PlayTools/Keymap/Keymapping.swift, PlayTools/PlayCover.swift, PlayTools/PlayLoader.m, PlayTools/PlaySettings.swift
Checked changing iOS model and keymapping working
=> refactor: Revamp to support new app setting plist

PlayTools.xcodeproj/project.pbxproj, PlayTools.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, PlayTools/DiscordActivity/DiscordActivity.swift, PlayTools/DiscordActivity/DiscordIPC.swift, PlayTools/PlayCover.swift, PlayTools/PlaySettings.swift
https://github.com/PlayCover/PlayCover/pull/49
=> feat: Implement Discord Activity(Rich Presence)

PlayTools/PlaySettings.swift
Added Model identifiers to playtools
=> Feat: ✨ Added iPhone 14 Pro Max and iPhone 13 Pro Max

PlayTools/DiscordActivity/DiscordIPC.swift
<h2>Changes to Discord RPC</h2>
**Updates:**
- Changed logo to new logo
- Added iTunes Lookup for app icons
=> Better Discord RPC

PlayTools/PlayScreen.swift
=> Fix macOS 13.2 Display Issue

PlayTools/Controls/PTFakeTouch/NSObject+Swizzle.m, PlayTools/PlayScreen.swift
**Changes:**
- We have full and consistent resolution control back (yipee)
**Known Issues:**
- App Default is still fucked for everything
=> ACTUALLY Fix 13.2 Issues

PlayTools/Controls/PTFakeTouch/NSObject+Swizzle.m, PlayTools/PlayScreen.swift
* Try swizzle orientation
* Remove old fix
* Swizzle everything
* Use actual values
* Fix for content inside of frame part 1
* Fix for content inside of frame part 2
* Whitespace n such
* More cleanup
---------
Co-authored-by: José Moreno <47700212+JoseMoreville@users.noreply.github.com>
=> ACTUALLY Fix 13.2 Issues (#75)

PlayTools.xcodeproj/project.pbxproj, PlayTools/Controls/PTFakeTouch/NSObject+Swizzle.m, PlayTools/Keymap/DragElementsView.swift, PlayTools/PlayLoader.m, PlayTools/PlayScreen.swift, PlayTools/PlaySettings.swift
cherry picked res fix and removal of rounded square mouse from circle menu, for 2.0.5 release.
=> Cherry pick for 2.0.5

PlayTools/Controls/PTFakeTouch/NSObject+Swizzle.m, PlayTools/PlaySettings.swift
Some apps: eg. NIKKE really do not want us to touch its window (will cause a crash/infinite loop if we do). This PR includes a mode that allows apps to do $whatever they want with the window
=> feat: alternate window fix mode for certain apps

PlayTools/Controls/PTFakeTouch/NSObject+Swizzle.m, PlayTools/PlayScreen.swift, PlayTools/PlaySettings.swift
Allows apps to run at not-2.0 scaling
=> feat: Custom resolution scaler

PlayTools/PlayLoader.m
Fixes the owl app, the anime game company lab app and many more™️ by handling cstrings in a never-before-seen way: correctly
=> fix: some cstrings in sysctls calls

PlayTools/MysticRunes/PlayedApple.swift, PlayTools/PlayLoader.m
(Finally) allow PlayChain to handle attributes (well, sorta)
=> feat!: PlayChain attributes support

PlayTools/MysticRunes/PlayedApple.swift
Seems like more investigation is needed as some apps are breaking.
=> Fix: revert PlayChain attr

PlayTools/Utils/Toast.swift
=> fix: make the Toast non-editable

PlayTools/Controls/PTFakeTouch/NSObject+Swizzle.m, PlayTools/MysticRunes/PlayShadow.m, PlayTools/MysticRunes/PlayedApple.swift, PlayTools/PlayCover.swift
=> feat: (attempt no. 2) allow PlayChain to handle attrs

PlayTools/PlaySettings.swift
See also: https://github.com/PlayCover/PlayCover/pull/1470
=> Add support for iPhone 15 Pro Max and 13" M4 iPad Pro

PlayTools/PlayLoader.m
This patch fix UnrealEngine 4's wrong file path in MacCatalyst.
Simply ignoring `Library/` from `Library//Users` of wrong path.
This patch is a temporary fix; I need to find out why UE4's IOSPath is incorrect.
Related Issues:
[PlayCover/PlayCover/issues/1478]
[PlayCover/PlayCover/issues/935]
=> Fix for UnrealEngine4's wrong file path

PlayTools/PlaySettings.swift
https://support.apple.com/en-mt/108044
=> Add support for iPhone 16 Pro Max

PlayTools/DiscordActivity/DiscordIPC.swift
Requires https://github.com/PlayCover/SwordRPC/pull/2.
=> Chore: update Discord IPC

PlayTools/Controls/MenuController.swift
This PR will keep track of the changes to make PlayTools compatible with MacOS Tahoe. Please point all merge requests for MacOS Tahoe to this branch.
=> MacOS Tahoe (26) Fix
